merge my request
rayriffy/mnet-api pull request #103
Opened 2019-07-07 06:54 UTC by porames

thanks

2019-07-08 01:58 UTC, rayriffy requested changes
API are migrating to **Node 12**, please rebase your repository before committing any changes.

2019-07-08 01:58 UTC, rayriffy commented on src/models/posts.js
> +    date: {
Please formatting all files correctly by according to ESLint rules.

2019-07-08 01:58 UTC, rayriffy commented on src/routes/v1/announce/list.js
> +	let payload = []
Why all spacings are changed?

2019-07-08 01:58 UTC, rayriffy commented on src/routes/v1/group/list.js
> +      var ownerId = groupList[index].owner
Security rules for Generic Object Injection Sink `eslint(security/detect-object-injection)` failed

2019-07-08 01:58 UTC, rayriffy commented on src/services/notify.js
> +        to: subscribers[i].user.token,
Security rules for Generic Object Injection Sink `eslint(security/detect-object-injection)` failed

2019-07-08 13:36 UTC, porames commented
linting fixed (I guess)

2019-07-08 14:59 UTC, rayriffy commented
Now, there're security warnings left from Codacy

2019-07-16 11:34 UTC, rayriffy commented
There's a conflict in `package.json` and `yarn.lock` and a lot of new issue being alerted from Codacy. I will close this PR.

Please open a new PR separately when your forked repo is up-to-date.

2019-07-16 11:34 UTC, closed without merging